# Generated by Django 4.0.1 on 2022-01-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
